/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 avatar.glb --transform 
Files: avatar.glb [923.8KB] > C:\Users\Aziz1\Documents\Aziz_AVATAR\3d-island-portfolio\public\avatar-transformed.glb [641.27KB] (31%)
*/

import React, { useEffect } from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';

export default function Avatar(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF('/avatar-transformed.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  console.log(actions, ':ACT');

  useEffect(() => {
    if (actions) {
      actions['GestureGreeting'].play();
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <primitive object={nodes.Root} />
        <group name="msm_glasses_3">
          <skinnedMesh
            name="msm_glasses_3_1"
            geometry={nodes.msm_glasses_3_1.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.msm_glasses_3_1.skeleton}
          />
          <skinnedMesh
            name="msm_glasses_3_2"
            geometry={nodes.msm_glasses_3_2.geometry}
            material={materials.PaletteMaterial002}
            skeleton={nodes.msm_glasses_3_2.skeleton}
          />
        </group>
        <group name="msm_hair_hat_C">
          <skinnedMesh
            name="msm_hair_hat_C_1"
            geometry={nodes.msm_hair_hat_C_1.geometry}
            material={materials.PaletteMaterial003}
            skeleton={nodes.msm_hair_hat_C_1.skeleton}
          />
          <skinnedMesh
            name="msm_hair_hat_C_2"
            geometry={nodes.msm_hair_hat_C_2.geometry}
            material={materials.PaletteMaterial003}
            skeleton={nodes.msm_hair_hat_C_2.skeleton}
          />
          <skinnedMesh
            name="msm_hair_hat_C_3"
            geometry={nodes.msm_hair_hat_C_3.geometry}
            material={materials.PaletteMaterial003}
            skeleton={nodes.msm_hair_hat_C_3.skeleton}
          />
        </group>
        <skinnedMesh
          name="msm_head_main"
          geometry={nodes.msm_head_main.geometry}
          material={materials.PaletteMaterial003}
          skeleton={nodes.msm_head_main.skeleton}
        />
        <group name="msm_pants_No3">
          <skinnedMesh
            name="msm_pants_No3_1"
            geometry={nodes.msm_pants_No3_1.geometry}
            material={materials.PaletteMaterial003}
            skeleton={nodes.msm_pants_No3_1.skeleton}
          />
          <skinnedMesh
            name="msm_pants_No3_2"
            geometry={nodes.msm_pants_No3_2.geometry}
            material={materials.PaletteMaterial003}
            skeleton={nodes.msm_pants_No3_2.skeleton}
          />
          <skinnedMesh
            name="msm_pants_No3_3"
            geometry={nodes.msm_pants_No3_3.geometry}
            material={materials.PaletteMaterial003}
            skeleton={nodes.msm_pants_No3_3.skeleton}
          />
        </group>
        <skinnedMesh
          name="msm_shoes_No16"
          geometry={nodes.msm_shoes_No16.geometry}
          material={materials.PaletteMaterial003}
          skeleton={nodes.msm_shoes_No16.skeleton}
        />
        <group name="msm_top_No31">
          <skinnedMesh
            name="msm_top_No31_1"
            geometry={nodes.msm_top_No31_1.geometry}
            material={materials.PaletteMaterial003}
            skeleton={nodes.msm_top_No31_1.skeleton}
          />
          <skinnedMesh
            name="msm_top_No31_2"
            geometry={nodes.msm_top_No31_2.geometry}
            material={materials.PaletteMaterial003}
            skeleton={nodes.msm_top_No31_2.skeleton}
          />
          <skinnedMesh
            name="msm_top_No31_3"
            geometry={nodes.msm_top_No31_3.geometry}
            material={materials.PaletteMaterial003}
            skeleton={nodes.msm_top_No31_3.skeleton}
          />
          <skinnedMesh
            name="msm_top_No31_4"
            geometry={nodes.msm_top_No31_4.geometry}
            material={materials.PaletteMaterial003}
            skeleton={nodes.msm_top_No31_4.skeleton}
          />
          <skinnedMesh
            name="msm_top_No31_5"
            geometry={nodes.msm_top_No31_5.geometry}
            material={materials.PaletteMaterial003}
            skeleton={nodes.msm_top_No31_5.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/avatar-transformed.glb');
