/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Gem Blue.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function GemBlue(props) {
  const { nodes, materials } = useGLTF('/pirate-kit/Gem Blue.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.UI_Gem_Blue.geometry}
        material={materials.Atlas}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload('/pirate-kit/Gem Blue.glb');
