/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Gem Pink.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function GemPink(props) {
  const { nodes, materials } = useGLTF('/pirate-kit/Gem Pink.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.UI_Gem_Pink.geometry}
        material={materials.Atlas}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload('/pirate-kit/Gem Pink.glb');
