/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\Island.glb --transform 
Files: .\public\Island.glb [6.9MB] > C:\Users\Aziz1\Documents\Aziz_AVATAR\3d-island-portfolio\Island-transformed.glb [521.96KB] (92%)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export default function IslandModel(props) {
  const { nodes, materials } = useGLTF('/Island-transformed.glb');
  return (
    <group
      {...props}
      dispose={null}
      scale={[0.1, 0.1, 0.1]}
      position={[0, -0.5, 0]}
      rotation={[0, 160, 0]}
    >
      <mesh
        geometry={nodes.Island.geometry}
        material={materials.Grass}
        position={[-3.045, 4.823, 0.808]}
        scale={[76.25, 88.035, 78.828]}
      />
      <mesh
        geometry={nodes.Fences.geometry}
        material={materials.PaletteMaterial001}
        position={[52.112, 6.876, -42.211]}
        rotation={[-Math.PI, -0.724, 0]}
        scale={[-0.195, -0.299, -0.97]}
      />
      <mesh
        geometry={nodes.Yellow_Flower.geometry}
        material={materials.PaletteMaterial002}
        position={[6.766, 5.377, -59.661]}
        rotation={[-1.775, -0.619, 1.228]}
        scale={[-0.052, -0.008, -0.051]}
      />
      <mesh
        geometry={nodes.Light_Pole_Lamp004.geometry}
        material={materials.PaletteMaterial003}
        position={[2.459, 19.761, -88.698]}
        rotation={[0, 1.502, 0]}
        scale={0.695}
      />
      <group
        position={[-26.68, 7.514, -61.843]}
        rotation={[0, -1.481, 0]}
        scale={[0.896, 1.496, 5.264]}
      >
        <mesh
          geometry={nodes.Cube004.geometry}
          material={materials.PaletteMaterial005}
        />
        <mesh
          geometry={nodes.Cube004_1.geometry}
          material={materials.PaletteMaterial006}
        />
        <mesh
          geometry={nodes.Cube004_2.geometry}
          material={materials.PaletteMaterial004}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/Island-transformed.glb');
