/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\island.glb --transform 
Files: .\public\island.glb [7.11MB] > C:\Users\Aziz1\Documents\Aziz_AVATAR\3d-island-portfolio\island-transformed.glb [2.19MB] (69%)
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export default function Island3D(props) {
  const { nodes, materials } = useGLTF('/island-transformed.glb');
  return (
    <group
      {...props}
      dispose={null}
      scale={[0.1, 0.1, 0.1]}
      position={[0, -0.75, 0]}
    >
      <group
        position={[42.197, 29.962, -3.068]}
        rotation={[1.634, -0.642, 0.018]}
        scale={[-1.299, -1.155, -0.295]}
      >
        <mesh
          geometry={nodes.House_Tile_Tile_Color_1_0002.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          geometry={nodes.House_Tile_Tile_Color_1_0002_1.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-38.414, 7.514, -38.821]}
        rotation={[-Math.PI, 0.556, -Math.PI]}
        scale={[0.896, 1.496, 5.264]}
      >
        <mesh
          geometry={nodes.Cube004.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          geometry={nodes.Cube004_1.geometry}
          material={materials.PaletteMaterial005}
        />
        <mesh
          geometry={nodes.Cube004_2.geometry}
          material={materials.PaletteMaterial003}
        />
      </group>
      <mesh
        geometry={nodes.Island.geometry}
        material={materials.Grass}
        position={[-3.045, 4.823, 0.808]}
        scale={[76.25, 88.035, 78.828]}
      />
      <mesh
        geometry={nodes.Light_Pole_Lamp.geometry}
        material={materials.PaletteMaterial006}
        position={[-6.595, 18.905, 19.083]}
        rotation={[-Math.PI, 1.469, -Math.PI]}
        scale={0.695}
      />
      <mesh
        geometry={nodes.Shop_Lamp.geometry}
        material={materials.PaletteMaterial007}
        position={[-32.127, 16.167, -38.265]}
        rotation={[Math.PI, -1.095, Math.PI]}
        scale={0.516}
      />
      <mesh
        geometry={nodes.Sea_Bottom.geometry}
        material={materials.PaletteMaterial008}
        position={[0.55, -3.683, 8.379]}
        scale={297.841}
      />
      <mesh
        geometry={nodes.House_Tile_Tile_Color_1_0002_Door_Metal_0.geometry}
        material={nodes.House_Tile_Tile_Color_1_0002_Door_Metal_0.material}
        position={[-54.174, 27.334, 2.06]}
        rotation={[-1.255, -1.531, 1.049]}
        scale={[0.896, 0.184, 0.952]}
      />
    </group>
  );
}

useGLTF.preload('/island-transformed.glb');
