/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 PropBottle.glb 
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export default function PropBottle(props) {
  const { nodes, materials } = useGLTF('/pirate-kit/PropBottle.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Prop_Bottle_1.geometry}
        material={materials.Atlas}
        scale={100}
        position={[0, -0.5, 0]}
      />
    </group>
  );
}

useGLTF.preload('/pirate-kit/PropBottle.glb');
